"""
Order document construction for the Redwood Retail dataset.

Orders are built per customer, in chronological order, so that every
"historical" metric written onto a document is computed from that customer's
actual prior orders rather than invented. ``daysSinceLastPurchase`` really is
the gap since the previous order; ``totalSpend90d`` really is the sum of orders
in the preceding 90 days.

This matters for two reasons. It makes the documents internally consistent, so
the mobile client and the agent can trust what they read. And it means the
BigQuery feature view can recompute the same quantities from raw order rows and
get the same answers, which is what allows churn to be labelled from observed
behaviour instead of from a rule.

The emitted schema is unchanged from the original generator, so the existing
BigQuery table, agent code and mobile client continue to work.
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from customer_profiles import Customer, SPEND_WINDOW_DAYS
from retail_catalog import (
    CATALOG_ITEMS,
    SHIPPING_CITIES,
    WAREHOUSES,
    CARRIERS,
    POSITIVE_FEEDBACK,
    NEUTRAL_FEEDBACK,
    NEGATIVE_FEEDBACK,
    COMPLAINT_REASONS,
    FEEDBACK_SENTIMENT_RANGES,
)

TAX_RATE = 0.21

# Discount applied at checkout by loyalty tier. This is the *standing* tier
# benefit only; retention offers generated by the agent are a separate,
# additive mechanism written to /loyalty_offers.
TIER_DISCOUNT_RATES = {
    "ENTERPRISE_VIP": 0.15,
    "PLATINUM": 0.12,
    "GOLD": 0.10,
    "SILVER": 0.05,
    "BRONZE": 0.02,
    "NONE": 0.0,
}

# Basket size by segment, driving order value separation between cohorts.
SEGMENT_BASKET = {
    "ENTERPRISE_VIP": (3, 8, 2, 6),
    "RETAIL_PRO": (2, 5, 1, 3),
    "STANDARD_LOYALTY": (1, 3, 1, 1),
    "CASUAL_SHOPPER": (1, 2, 1, 1),
}


def _rating_to_sentiment(rating: int, rng: random.Random) -> float:
    if rating >= 4:
        lo, hi = FEEDBACK_SENTIMENT_RANGES["POSITIVE"]
    elif rating == 3:
        lo, hi = FEEDBACK_SENTIMENT_RANGES["NEUTRAL"]
    else:
        lo, hi = FEEDBACK_SENTIMENT_RANGES["NEGATIVE"]
    return round(rng.uniform(lo, hi), 3)


def _feedback_text(rating: int, rng: random.Random) -> str:
    if rating >= 4:
        return rng.choice(POSITIVE_FEEDBACK)
    if rating == 3:
        return rng.choice(NEUTRAL_FEEDBACK)
    return rng.choice(NEGATIVE_FEEDBACK)


def _decline_factor(customer: Customer, order_date: datetime, dates: List[datetime]) -> float:
    """Scale order value down over time for deteriorating customers.

    Returns 1.0 for stable archetypes. For declining ones the basket shrinks
    towards 45% of its original size by the end of the history, which gives the
    monetary dimension of RFM something real to detect.
    """
    if not customer.archetype.declining or len(dates) < 2:
        return 1.0
    span = (dates[-1] - dates[0]).days or 1
    progress = (order_date - dates[0]).days / span
    return 1.0 - (0.55 * progress)


def build_order(
    customer: Customer,
    order_date: datetime,
    sequence: int,
    rng: random.Random,
    prior_orders: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build one order document for ``customer`` at ``order_date``.

    ``prior_orders`` must contain the customer's already-generated orders, in
    chronological order; recency, frequency and monetary features are derived
    from it.
    """
    order_id = (
        f"ORD-{order_date.strftime('%y%m')}-"
        f"{customer.customer_id.split('_')[-1].upper()}-{sequence:04d}"
    )

    min_items, max_items, min_qty, max_qty = SEGMENT_BASKET.get(
        customer.customer_segment, (1, 3, 1, 2)
    )
    num_items = rng.randint(min_items, max_items)
    qty_multiplier = rng.randint(min_qty, max_qty)

    decline = _decline_factor(customer, order_date, customer.order_dates)
    spend_scale = customer.archetype.spend_multiplier * decline

    selected = rng.sample(CATALOG_ITEMS, min(num_items, len(CATALOG_ITEMS)))
    line_items: List[Dict[str, Any]] = []
    subtotal = 0.0
    total_cost = 0.0
    total_weight = 0.0

    for prod in selected:
        qty = max(1, int(rng.randint(1, 3) * qty_multiplier * decline))
        item_total = round(qty * prod["unitPrice"], 2)
        subtotal += item_total
        total_cost += round(qty * prod["cost"], 2)
        total_weight += round(qty * rng.uniform(1.2, 14.5), 2)
        line_items.append({
            "sku": prod["sku"],
            "name": prod["name"],
            "category": prod["category"],
            "quantity": qty,
            "unitPrice": prod["unitPrice"],
            "totalPrice": item_total,
            "allocatedWarehouse": rng.choice(WAREHOUSES),
        })

    subtotal = round(subtotal * max(spend_scale, 0.25), 2)
    total_cost = round(total_cost * max(spend_scale, 0.25), 2)

    tax_amount = round(subtotal * TAX_RATE, 2)
    shipping_fee = round(rng.choice([0.0, 45.0, 95.0, 150.0, 220.0]), 2)
    discount_total = round(subtotal * TIER_DISCOUNT_RATES.get(customer.loyalty_tier, 0.0), 2)
    grand_total = round(subtotal - discount_total + tax_amount + shipping_fee, 2)
    profit_margin = round(
        (grand_total - total_cost - tax_amount) / max(grand_total, 1.0), 3
    )

    # ---- Derived history, computed from this customer's real prior orders ----
    if prior_orders:
        last_dt = datetime.fromisoformat(prior_orders[-1]["createdAt"])
        days_since_last_purchase = max((order_date - last_dt).days, 0)
    else:
        # First ever order: recency is measured from account creation instead.
        days_since_last_purchase = min(customer.account_age_days, 365)

    spend_cutoff = order_date - timedelta(days=SPEND_WINDOW_DAYS)
    year_cutoff = order_date - timedelta(days=365)

    total_spend_90d = round(sum(
        o["financials"]["grandTotal"]
        for o in prior_orders
        if datetime.fromisoformat(o["createdAt"]) >= spend_cutoff
    ), 2)

    orders_count_12m = sum(
        1 for o in prior_orders
        if datetime.fromisoformat(o["createdAt"]) >= year_cutoff
    )

    prior_totals = [o["financials"]["grandTotal"] for o in prior_orders]
    avg_order_value = round(
        sum(prior_totals) / len(prior_totals), 2
    ) if prior_totals else grand_total

    lifetime_spend = round(sum(prior_totals) + grand_total, 2)

    if len(prior_orders) >= 2:
        first_dt = datetime.fromisoformat(prior_orders[0]["createdAt"])
        months = max((order_date - first_dt).days / 30.0, 1.0)
        purchase_frequency_monthly = round(len(prior_orders) / months, 2)
    else:
        purchase_frequency_monthly = 0.0

    # ---- Satisfaction ----
    ratings = customer.archetype.feedback_rating_weights
    rating = rng.choices(list(ratings.keys()), weights=list(ratings.values()), k=1)[0]
    sentiment_score = _rating_to_sentiment(rating, rng)
    has_complaint = rating <= 2
    complaint_reason = rng.choice(COMPLAINT_REASONS) if has_complaint else None

    if rating <= 2:
        order_status = rng.choice(["DELIVERED", "CANCELLED", "SHIPPED"])
        payment_status = rng.choice(["SETTLED", "REFUNDED"])
    else:
        order_status = rng.choice(["DELIVERED", "SHIPPED"])
        payment_status = "SETTLED"

    if customer.city:
        city_data = next(
            (c for c in SHIPPING_CITIES if c["city"] == customer.city),
            SHIPPING_CITIES[0],
        )
    else:
        city_data = rng.choice(SHIPPING_CITIES)

    updated_at = order_date + timedelta(minutes=rng.randint(5, 45))
    est_delivery = order_date + timedelta(days=rng.randint(1, 4))

    return {
        "_id": order_id,
        "orderId": order_id,
        "customerId": customer.customer_id,
        "customerName": customer.customer_name,
        "customerEmail": customer.customer_email,
        "customerSegment": customer.customer_segment,
        "orderStatus": order_status,
        "paymentStatus": payment_status,
        "paymentMethod": rng.choice(
            ["INVOICE_NET30", "CREDIT_CARD", "IDEAL", "SEPA_DIRECT_DEBIT"]
        ),
        "currency": "EUR",
        "financials": {
            "subtotal": subtotal,
            "taxAmount": tax_amount,
            "shippingFee": shipping_fee,
            "discountTotal": discount_total,
            "grandTotal": grand_total,
            "profitMargin": profit_margin,
        },
        "transactionalMetrics": {
            "totalSpend90d": total_spend_90d,
            "lifetimeSpend": lifetime_spend,
            "avgOrderValue": avg_order_value,
            "purchaseFrequencyMonthly": purchase_frequency_monthly,
            "daysSinceLastPurchase": days_since_last_purchase,
            "ordersCountLast12m": orders_count_12m,
        },
        "engagement": {
            "loginFrequencyMonthly": customer.login_frequency_monthly,
            "avgSessionDurationMinutes": customer.avg_session_duration_minutes,
            "appEngagementScore": customer.app_engagement_score,
            "appSessionsLast30d": customer.app_sessions_last_30d,
            "cartAbandonmentCount": customer.cart_abandonment_count,
            "abandonedCartValue90d": customer.abandoned_cart_value_90d,
        },
        "supportMetrics": {
            "supportTicketsCount": customer.support_tickets_count,
            "openSupportTicketsCount": customer.open_support_tickets_count,
            "complaintsCount": customer.complaints_count,
            "returnFrequency": customer.return_frequency,
            "returnRatePercent": customer.return_rate_percent,
            "sentimentScore": sentiment_score,
            "hasActiveComplaint": has_complaint,
            "primaryComplaintReason": complaint_reason,
        },
        "accountState": {
            "loyaltyTier": customer.loyalty_tier,
            "isLoyaltyMember": customer.is_loyalty_member,
            "accountAgeDays": customer.account_age_days,
            "customerSegment": customer.customer_segment,
        },
        "logistics": {
            "carrierCode": rng.choice(CARRIERS),
            "serviceLevel": rng.choice(
                ["NEXT_DAY_AIR", "STANDARD_FREIGHT", "EXPRESS_PARCEL"]
            ),
            "originHub": rng.choice(WAREHOUSES),
            "totalWeightKg": round(total_weight, 2),
            "requireSignature": True,
        },
        "shippingAddress": {
            "streetAddress": f"Industrial Park Way {rng.randint(10, 800)}",
            "city": city_data["city"],
            "province": city_data["province"],
            "postalCode": city_data["postalCode"],
            "countryCode": city_data["countryCode"],
        },
        "lineItems": line_items,
        "customerFeedback": {
            "feedbackText": _feedback_text(rating, rng),
            "rating": rating,
            "sentimentScore": sentiment_score,
            "channel": rng.choice(
                ["MOBILE_APP", "CHATBOT", "EMAIL_SURVEY", "WEB_PORTAL"]
            ),
            "hasActiveComplaint": has_complaint,
            "primaryComplaintReason": complaint_reason,
            "feedbackTimestamp": order_date.isoformat(),
        },
        "metadata": {
            "apiVersion": "v2.0",
            "sourcePlatform": rng.choice(
                ["ERP_SAP_CONNECTOR", "CUSTOM_MOBILE_APP", "COMMERCE_PORTAL"]
            ),
            "clientIpAddress": (
                f"10.{rng.randint(10, 99)}.{rng.randint(1, 254)}.{rng.randint(1, 254)}"
            ),
            "retryCount": 0,
        },
        "createdAt": order_date.isoformat(),
        "updatedAt": updated_at.isoformat(),
        "estimatedDeliveryDate": est_delivery.isoformat(),
    }


def build_customer_orders(customer: Customer, rng: random.Random) -> List[Dict[str, Any]]:
    """Build the full chronological order history for one customer."""
    orders: List[Dict[str, Any]] = []
    for seq, order_date in enumerate(customer.order_dates, start=1):
        orders.append(build_order(customer, order_date, seq, rng, orders))
    return orders


def build_customer_document(
    customer: Customer,
    orders: List[Dict[str, Any]],
    now: datetime,
) -> Dict[str, Any]:
    """Build the ``/customers/{customerId}`` profile document.

    This collection was never created by the previous seeder even though the
    agent reads it on every evaluation, which meant every lookup fell through to
    the cold-start heuristic. Populating it gives the agent real context.

    Note that ``baselineChurnRisk`` is deliberately omitted. The agent must
    source churn from the BigQuery model output, and a cached value here would
    shadow it.
    """
    totals = [o["financials"]["grandTotal"] for o in orders]
    last_order_dt = (
        datetime.fromisoformat(orders[-1]["createdAt"]) if orders else None
    )

    doc: Dict[str, Any] = {
        "customerId": customer.customer_id,
        "customerName": customer.customer_name,
        "customerEmail": customer.customer_email,
        "customerSegment": customer.customer_segment,
        "loyaltyTier": customer.loyalty_tier,
        "isLoyaltyMember": bool(customer.is_loyalty_member),
        "accountAgeDays": customer.account_age_days,
        "lifetimeSpend": round(sum(totals), 2),
        "ordersCount": len(orders),
        "lastOrderAt": last_order_dt.isoformat() if last_order_dt else None,
        "daysSinceLastPurchase": (
            (now - last_order_dt).days if last_order_dt else None
        ),
        "engagement": {
            "loginFrequencyMonthly": customer.login_frequency_monthly,
            "avgSessionDurationMinutes": customer.avg_session_duration_minutes,
            "appEngagementScore": customer.app_engagement_score,
            "cartAbandonmentCount": customer.cart_abandonment_count,
        },
        "supportMetrics": {
            "supportTicketsCount": customer.support_tickets_count,
            "openSupportTicketsCount": customer.open_support_tickets_count,
            "complaintsCount": customer.complaints_count,
            "returnRatePercent": customer.return_rate_percent,
        },
        "updatedAt": now.isoformat(),
    }

    # Demo personas carry the IAM principal they are reachable by, so the
    # client can resolve a signed-in service account to its customer record.
    if customer.iam_principal:
        doc["iamPrincipal"] = customer.iam_principal
        doc["isDemoPersona"] = True

    return doc
